#!/usr/bin/env bash
# =============================================================================
#                       ********* SETUP ROUTINE *********                      
#            Infrastructure provisioning and dependency resolution.            
# =============================================================================
# Step 1 — Ollama, and the model the paper was measured on.
#
# Enforce exact model configuration parameters for strict reproducibility.

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

say "ollama"

if have ollama; then
    ok "already installed ($(ollama --version 2>/dev/null | head -1))"
else
    info "installing from ollama.com (official script, installs to /usr/local/bin)"
    curl -fsSL https://ollama.com/install.sh | sh >"$SETUP_LOG_DIR/ollama-install.log" 2>&1 \
        || die "ollama install failed; see $SETUP_LOG_DIR/ollama-install.log"
    have ollama || die "ollama not on PATH after install"
    ok "installed"
    # Wait for asynchronous systemd unit registration to complete.
    SUDO=""; [ "$(id -u)" -ne 0 ] && SUDO="sudo"
    $SUDO systemctl daemon-reload 2>/dev/null || true
    for _ in $(seq 1 15); do
        systemctl list-unit-files 2>/dev/null | grep -q '^ollama\.service' && break
        sleep 1
    done
fi

# =============================================================================
#                       ********* SERVER START *********                       
#                 Enforce precise pipeline caching parameters.                 
# =============================================================================

KV_CACHE="${KV_CACHE:-q4_0}"
VRAM="$(cat "$SETUP_LOG_DIR/vram.mib" 2>/dev/null || gpu_vram_mib)"
if [ "${VRAM:-0}" -ge 8000 ] && [ "$KV_CACHE" = "q4_0" ]; then
    info "VRAM sufficient for f16 KV cache. Pinning q4_0 per manuscript constraints."
fi

# Configure OLLAMA_KV_CACHE_TYPE and OLLAMA_FLASH_ATTENTION in systemd drop-in.
if systemctl list-unit-files 2>/dev/null | grep -q '^ollama\.service'; then
    info "ollama is systemd-managed -- writing a drop-in override"
    SUDO=""; [ "$(id -u)" -ne 0 ] && SUDO="sudo"
    $SUDO mkdir -p /etc/systemd/system/ollama.service.d
    $SUDO tee /etc/systemd/system/ollama.service.d/acv.conf >/dev/null <<EOF
# Generated by setup/10-ollama.sh. Do not edit.
[Service]
Environment="OLLAMA_FLASH_ATTENTION=1"
Environment="OLLAMA_KV_CACHE_TYPE=$KV_CACHE"
EOF
    $SUDO systemctl daemon-reload
    $SUDO systemctl restart ollama
    for _ in $(seq 1 30); do
        sleep 1
        curl -sf -m 2 http://localhost:11434/api/version >/dev/null 2>&1 && break
    done
    ACTUAL="$(systemctl show ollama -p Environment 2>/dev/null | tr ' ' '\n' \
              | grep OLLAMA_KV_CACHE_TYPE | cut -d= -f2 || true)"
    [ "$ACTUAL" = "$KV_CACHE" ] \
        && ok "systemd unit now serves with KV cache=$ACTUAL, flash attention on" \
        || die "override did not take: unit reports KV_CACHE='${ACTUAL:-unset}'"
elif curl -sf -m 2 http://localhost:11434/api/version >/dev/null 2>&1; then
    # Refuse initialization if conflicting server port is already bound.
    OWNER="$(ps -o user= -p "$(pgrep -f 'ollama serve' | head -1 || true)" 2>/dev/null | tr -d ' ' || true)"
    die "a server (user=${OWNER:-?}) already holds :11434 and was not configured by this
   step. Stop and restart to enforce cache type:
       sudo systemctl stop ollama 2>/dev/null; pkill -f 'ollama serve'
       bash setup/10-ollama.sh"
else
    info "starting ollama serve (KV cache=$KV_CACHE, flash attention on)"
    mkdir -p "$ACV_ROOT/logs"
    OLLAMA_FLASH_ATTENTION=1 OLLAMA_KV_CACHE_TYPE="$KV_CACHE" \
        setsid nohup ollama serve >"$ACV_ROOT/logs/ollama-serve.log" 2>&1 </dev/null &
    for _ in $(seq 1 30); do
        sleep 1
        curl -sf -m 2 http://localhost:11434/api/version >/dev/null 2>&1 && break
    done
    curl -sf -m 2 http://localhost:11434/api/version >/dev/null 2>&1 \
        || die "server did not come up; see $ACV_ROOT/logs/ollama-serve.log"
    ok "serving"
fi

# =============================================================================
#                ********* CONFIGURATION VERIFICATION *********                
#                 Validate running server execution parameters.                
# =============================================================================

SERVE_PID="$(ss -lptnH 'sport = :11434' 2>/dev/null \
             | grep -o 'pid=[0-9]*' | head -1 | cut -d= -f2 || true)"
if [ -n "$SERVE_PID" ]; then
    # Isolate privileged file handle reading to process environment verification.
    EFFECTIVE="$(sudo cat "/proc/$SERVE_PID/environ" 2>/dev/null | tr '\0' '\n' \
                 | grep '^OLLAMA_KV_CACHE_TYPE=' | cut -d= -f2 || true)"
    if [ -z "$EFFECTIVE" ]; then
        die "the server on :11434 (pid $SERVE_PID) has no OLLAMA_KV_CACHE_TYPE set: override failed."
    elif [ "$EFFECTIVE" != "$KV_CACHE" ]; then
        die "server on :11434 is serving KV cache '$EFFECTIVE', not '$KV_CACHE'"
    else
        ok "verified: the listening server (pid $SERVE_PID) uses KV cache=$EFFECTIVE"
    fi
else
    warn "could not identify the process on :11434 -- cache type unverified"
fi

# =============================================================================
#                        ********* MODEL SYNC *********                        
#                        Download and register weights.                        
# =============================================================================

say "model: $MODEL"

if ollama list 2>/dev/null | awk '{print $1}' | grep -qx "$MODEL"; then
    ok "already pulled"
else
    info "pulling (~2.5 GB) -- this is the slow step"
    ollama pull "$MODEL" 2>&1 | tail -3 || die "pull failed"
    ok "pulled"
fi

# =============================================================================
#                        ********* PROVENANCE *********                        
# Validate quantization and parameters against published manuscript constraints.
# =============================================================================

QUANT="$(ollama show "$MODEL" 2>/dev/null | awk 'tolower($0) ~ /quantization/ {print $NF; exit}' || true)"
DIGEST="$(ollama list 2>/dev/null | awk -v m="$MODEL" '$1==m {print $2; exit}' || true)"
PARAMS="$(ollama show "$MODEL" 2>/dev/null | awk 'tolower($0) ~ /parameters/ {print $NF; exit}' || true)"

{
    echo "model        $MODEL"
    echo "quantization ${QUANT:-unknown}"
    echo "parameters   ${PARAMS:-unknown}"
    echo "digest       ${DIGEST:-unknown}"
    echo "kv_cache     $KV_CACHE"
    echo "recorded     $(date -Is)"
    echo "host         $(hostname)"
} | tee "$ACV_ROOT/logs/setup/model-provenance.txt" | sed 's/^/   /'

case "${QUANT^^}" in
    Q4_K_M) ok "quantisation matches the manuscript" ;;
    "")     warn "could not read the quantisation from \`ollama show\`" ;;
    *)      warn "quantisation is $QUANT, the manuscript used Q4_K_M."
            warn "results will not be directly comparable. To force it:"
            warn "  ollama pull ${MODEL%%:*}:4b-q4_K_M" ;;
esac
